package org.example;
// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;

import org.junit.jupiter.api.*;
import org.openqa.selenium.firefox.FirefoxOptions;

import java.util.HashMap;
import java.util.Map;

public class TestGoogleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    //driver = new FirefoxDriver();
    String os = System.getProperty("os.name").toLowerCase();
    boolean unixOS = os.contains("nux");
    if (unixOS) {
      FirefoxOptions options = new FirefoxOptions();
      //ChromeOptions options = new ChromeOptions();
      // setting headless mode to true.. so there isn't any ui
      options.addArguments("--headless", "--no-sandbox");
      //options.addArguments("--no-sandbox");
      driver = new FirefoxDriver(options);
    } else {
      driver = new FirefoxDriver();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void testGoogle() {
    driver.get("https://www.google.com/");
    //driver.manage().window().setSize(new Dimension(1376, 1032));
    driver.manage().window().maximize();
    driver.findElement(By.id("W0wltc")).click();
    driver.findElement(By.id("APjFqb")).click();
    driver.findElement(By.id("APjFqb")).sendKeys("abc");
    driver.findElement(By.name("btnK")).click();
  }
}
