package org.example;
// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;

import org.junit.jupiter.api.*;

import java.util.HashMap;
import java.util.Map;

public class TestGoogleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void testGoogle() {
    driver.get("https://www.google.com/");
    //driver.manage().window().setSize(new Dimension(1376, 1032));
    driver.manage().window().maximize();
    driver.findElement(By.id("W0wltc")).click();
    driver.findElement(By.id("APjFqb")).click();
    driver.findElement(By.id("APjFqb")).sendKeys("abc");
    driver.findElement(By.name("btnK")).click();
  }
}
